export const FIRST_ACCESS_REQUEST = 'FIRST_ACCESS_REQUEST';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const FORM_LOGIN_REQUEST = 'FORM_LOGIN_REQUEST';
export const FORM_LOGIN_REQUEST_SUCCESS = 'FORM_LOGIN_REQUEST_SUCCESS';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_REQUEST_SUCCESS = 'LOGOUT_REQUEST_SUCCESS';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_REQUEST_SUCCESS = 'REGISTER_REQUEST_SUCCESS';
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_REQUEST_SUCCESS = 'REGISTER_USER_REQUEST_SUCCESS';

export const ACTIVITY_INDICATOR_TOGGLE = 'ACTIVITY_INDICATOR_TOGGLE';
export const ACTIVITY_INDICATOR_SHOW = 'ACTIVITY_INDICATOR_SHOW';
export const ACTIVITY_INDICATOR_HIDE = 'ACTIVITY_INDICATOR_HIDE';

export const ALERT_ERROR = 'ALERT_ERROR';
export const ALERT_SUCCESS = 'ALERT_SUCCESS';

export const NAVIGATE = 'Navigation/NAVIGATE';
export const RESET_NAVIGATION = 'Navigation/RESET';
export const BACK = 'Navigation/BACK';

export const ME_REQUEST = 'ME_REQUEST';
export const ME_REQUEST_SUCCESS = 'ME_REQUEST_SUCCESS';
export const ME_UPDATE_REQUEST = 'ME_UPDATE_REQUEST';
export const ME_UPDATE_REQUEST_SUCCESS = 'ME_UPDATE_REQUEST_SUCCESS';
export const ME_DELETE_REQUEST = 'ME_DELETE_REQUEST';
export const ME_REQUEST_PASSWORD = 'ME_REQUEST_PASSWORD';
export const ME_RESET_PASSWORD = 'ME_RESET_PASSWORD';

export const LOGIN_WITH_FACEBOOK_REQUEST = 'LOGIN_WITH_FACEBOOK_REQUEST';
export const LOGIN_WITH_FACEBOOK_REQUEST_SUCCESS =
  'LOGIN_WITH_FACEBOOK_REQUEST_SUCCESS';

export const REACTION_SEND_REQUEST = 'REACTION_SEND_REQUEST';
export const REACTION_SEND_REQUEST_SUCCESS = 'REACTION_SEND_REQUEST_SUCCESS';

export const ACTION_REQUEST = 'ACTION_REQUEST';
export const ACTION_REQUEST_SUCCESS = 'ACTION_REQUEST_SUCCESS';
export const ACTIONS_HISTORY_REQUEST = 'ACTIONS_HISTORY_REQUEST';
export const ACTIONS_HISTORY_REQUEST_SUCCESS =
  'ACTIONS_HISTORY_REQUEST_SUCCESS';
export const ACTION_SUBSCRIBE_REQUEST = 'ACTION_SUBSCRIBE_REQUEST';
export const ACTION_SUBSCRIBE_REQUEST_SUCCESS =
  'ACTION_SUBSCRIBE_REQUEST_SUCCESS';
export const ACTION_UPDATE_REQUEST = 'ACTION_UPDATE_REQUEST';
export const ACTION_UPDATE_REQUEST_SUCCESS = 'ACTION_UPDATE_REQUEST_SUCCESS';
export const ACTION_TERMS_REQUEST = 'ACTION_TERMS_REQUEST';
export const ACTION_TERMS_REQUEST_SUCCESS = 'ACTION_TERMS_REQUEST_SUCCESS';
export const ACTION_RESET_REQUEST = 'ACTION_RESET_REQUEST';

export const STAMPS_REQUEST = 'STAMPS_REQUEST';
export const STAMPS_REQUEST_SUCCESS = 'STAMPS_REQUEST_SUCCESS';

export const RANKING_REQUEST = 'RANKING_REQUEST';
export const RANKING_REQUEST_SUCCESS = 'RANKING_REQUEST_SUCCESS';
export const RANKING_RESET_REQUEST = 'RANKING_RESET_REQUEST';
export const RANKING_RESET_REQUEST_SUCCESS = 'RANKING_RESET_REQUEST_SUCCESS';

export const PRIZES_REQUEST = 'PRIZES_REQUEST';
export const PRIZES_REQUEST_SUCCESS = 'PRIZES_REQUEST_SUCCESS';
export const PRIZE_CONFIRM_REQUEST = 'PRIZE_CONFIRM_REQUEST';
export const PRIZE_CONFIRM_REQUEST_SUCCESS = 'PRIZE_CONFIRM_REQUEST_SUCCESS';
export const PRIZES_RESET_REQUEST = 'PRIZES_RESET_REQUEST';
export const PRIZES_RESET_REQUEST_SUCCESS = 'PRIZES_RESET_REQUEST_SUCCESS';

export const CONNECTION_CHANGED = 'CONNECTION_CHANGED';

export const SALES_HISTORY_REQUEST = 'SALES_HISTORY_REQUEST';
export const SALES_HISTORY_REQUEST_SUCCESS = 'SALES_HISTORY_REQUEST_SUCCESS';

export const SALE_LOCAL_DELETE_REQUEST = 'SALE_LOCAL_DELETE_REQUEST';
export const SALE_LOCAL_DELETE_REQUEST_SUCCESS =
  'SALE_LOCAL_DELETE_REQUEST_SUCCESS';
export const SALE_LOCAL_CREATE_REQUEST = 'SALE_LOCAL_CREATE_REQUEST';
export const SALE_LOCAL_CREATE_REQUEST_SUCCESS =
  'SALE_LOCAL_CREATE_REQUEST_SUCCESS';
export const SALE_SINCRONIZE_REQUEST = 'SALE_SINCRONIZE_REQUEST';
export const SALE_SINCRONIZE_REQUEST_SUCCESS =
  'SALE_SINCRONIZE_REQUEST_SUCCESS';
export const SALES_INCREMENT_LAST_SALE_ID = 'SALES_INCREMENT_LAST_SALE_ID';
export const SALES_INCREMENT_LAST_SALE_ID_SUCCESS =
  'SALES_INCREMENT_LAST_SALE_ID_SUCCESS';
export const SALE_FEEDBACK_RESET_REQUEST = 'SALE_FEEDBACK_RESET_REQUEST';

export const CUSTOMERS_REQUEST = 'CUSTOMERS_REQUEST';
export const CUSTOMERS_REQUEST_SUCCESS = 'CUSTOMERS_REQUEST_SUCCESS';
export const CUSTOMER_CREATE_REQUEST = 'CUSTOMER_CREATE_REQUEST';
export const CUSTOMER_CREATE_REQUEST_SUCCESS =
  'CUSTOMER_CREATE_REQUEST_SUCCESS';
export const CUSTOMER_SALE_REQUEST = 'CUSTOMER_SALE_REQUEST';
export const CUSTOMER_SALE_REQUEST_SUCCESS = 'CUSTOMER_SALE_REQUEST_SUCCESS';
export const CUSTOMER_SALE_RESET_REQUEST = 'CUSTOMER_SALE_RESET_REQUEST';
export const CUSTOMER_SALE_RESET_REQUEST_SUCCESS =
  'CUSTOMER_SALE_RESET_REQUEST_SUCCESS';
export const CUSTOMER_UPDATE_REQUEST = 'CUSTOMER_UPDATE_REQUEST';
export const CUSTOMER_UPDATE_REQUEST_SUCCESS =
  'CUSTOMER_UPDATE_REQUEST_SUCCESS';

export const FAQ_REQUEST = 'FAQ_REQUEST';
export const FAQ_REQUEST_SUCCESS = 'FAQ_REQUEST_SUCCESS';

export const NEWS_REQUEST = 'NEWS_REQUEST';
export const NEWS_REQUEST_SUCCESS = 'NEWS_REQUEST_SUCCESS';
export const NEWS_DETAIL_REQUEST = 'NEWS_DETAIL_REQUEST';
export const NEWS_DETAIL_REQUEST_SUCCESS = 'NEWS_DETAIL_REQUEST_SUCCESS';

export const LOOK_BOOKS_REQUEST = 'LOOK_BOOKS_REQUEST';
export const LOOK_BOOKS_REQUEST_SUCCESS = 'LOOK_BOOKS_REQUEST_SUCCESS';
export const LOOK_BOOK_DETAIL_REQUEST = 'LOOK_BOOK_DETAIL_REQUEST';
export const LOOK_BOOK_DETAIL_REQUEST_SUCCESS =
  'LOOK_BOOK_DETAIL_REQUEST_SUCCESS';

export const VMS_REQUEST = 'VMS_REQUEST';
export const VMS_REQUEST_SUCCESS = 'VMS_REQUEST_SUCCESS';
export const VM_DETAIL_REQUEST = 'VM_DETAIL_REQUEST';
export const VM_DETAIL_REQUEST_SUCCESS = 'VM_DETAIL_REQUEST_SUCCESS';

export const TRAINNINGS_REQUEST = 'TRAINNINGS_REQUEST';
export const TRAINNINGS_REQUEST_SUCCESS = 'TRAINNINGS_REQUEST_SUCCESS';

export const STYLES_REQUEST = 'STYLES_REQUEST';
export const STYLES_REQUEST_SUCCESS = 'STYLES_REQUEST_SUCCESS';
export const STYLE_DETAIL_REQUEST = 'STYLE_DETAIL_REQUEST';
export const STYLE_DETAIL_REQUEST_SUCCESS = 'STYLE_DETAIL_REQUEST_SUCCESS';

export const SHOW_CASES_REQUEST = 'SHOW_CASES_REQUEST';
export const SHOW_CASES_REQUEST_SUCCESS = 'SHOW_CASES_REQUEST_SUCCESS';
export const SHOW_CASE_DETAIL_REQUEST = 'SHOW_CASE_DETAIL_REQUEST';
export const SHOW_CASE_DETAIL_REQUEST_SUCCESS =
  'SHOW_CASE_DETAIL_REQUEST_SUCCESS';

export const VIDEOS_REQUEST = 'VIDEOS_REQUEST';
export const VIDEOS_REQUEST_SUCCESS = 'VIDEOS_REQUEST_SUCCESS';

export const TERMS_REQUEST = 'TERMS_REQUEST';
export const TERMS_REQUEST_SUCCESS = 'TERMS_REQUEST_SUCCESS';
export const USER_TERMS_REQUEST = 'USER_TERMS_REQUEST';
export const USER_TERMS_REQUEST_SUCCESS = 'USER_TERMS_REQUEST_SUCCESS';
export const TERMS_ACCEPT_REQUEST = 'TERMS_ACCEPT_REQUEST';
export const TERMS_ACCEPT_REQUEST_SUCCESS = 'TERMS_ACCEPT_REQUEST_SUCCESS';

export const NOTIFICATIONS_REQUEST = 'NOTIFICATIONS_REQUEST';
export const NOTIFICATIONS_REQUEST_SUCCESS = 'NOTIFICATIONS_REQUEST_SUCCESS';
export const NOTIFICATIONS_ARCHIVE_REQUEST = 'NOTIFICATIONS_ARCHIVE_REQUEST';
export const NOTIFICATIONS_ARCHIVE_REQUEST_SUCCESS =
  'NOTIFICATIONS_ARCHIVE_REQUEST_SUCCESS';

export const S3_SEND_REQUEST = 'S3_SEND_REQUEST';
export const S3_SEND_REQUEST_SUCCESS = 'S3_SEND_REQUEST_SUCCESS';

export const PILOT_LAST_FOLDER_REQUEST = 'PILOT_LAST_FOLDER_REQUEST';
export const PILOT_FOLDERS_REQUEST = 'PILOT_FOLDERS_REQUEST';
export const PILOT_FOLDERS_REQUEST_SUCCESS = 'PILOT_FOLDERS_REQUEST_SUCCESS';

export const USER_DEVICE_SAVE_REQUEST = 'USER_DEVICE_SAVE_REQUEST';
export const USER_DEVICE_SAVE_REQUEST_SUCCESS =
  'USER_DEVICE_SAVE_REQUEST_SUCCESS';
export const USER_DEVICE_SEND_REQUEST = 'USER_DEVICE_SEND_REQUEST';
export const USER_DEVICE_SEND_REQUEST_SUCCESS =
  'USER_DEVICE_SEND_REQUEST_SUCCESS';

export const VERSION_REQUEST = 'VERSION_REQUEST';
export const VERSION_REQUEST_SUCCESS = 'VERSION_REQUEST_SUCCESS';
export const VERSION_SEND_REQUEST = 'VERSION_SEND_REQUEST';
export const VERSION_SEND_REQUEST_SUCCESS = 'VERSION_SEND_REQUEST_SUCCESS';

export const DEVOLUTION_SINCRONIZE_REQUEST = 'DEVOLUTION_SINCRONIZE_REQUEST';
export const DEVOLUTION_SINCRONIZE_REQUEST_SUCCESS =
  'DEVOLUTION_SINCRONIZE_REQUEST_SUCCESS';
export const DEVOLUTIONS_HISTORY_REQUEST = 'DEVOLUTIONS_HISTORY_REQUEST';
export const DEVOLUTIONS_HISTORY_REQUEST_SUCCESS =
  'DEVOLUTIONS_HISTORY_REQUEST_SUCCESS';

export const CHAT_REQUEST = 'CHAT_REQUEST';
export const CHAT_REQUEST_SUCCESS = 'CHAT_REQUEST_SUCCESS';
export const CHAT_SEND_REQUEST = 'CHAT_SEND_REQUEST';
export const CHAT_SEND_REQUEST_SUCCESS = 'CHAT_SEND_REQUEST_SUCCESS';
export const CHAT_SAVE_REQUEST = 'CHAT_SAVE_REQUEST';
export const CHAT_RESET_REQUEST = 'CHAT_RESET_REQUEST';
export const CHAT_PUSH_LOCK_REQUEST = 'CHAT_PUSH_LOCK_REQUEST';
export const CHAT_PUSH_UNLOCK_REQUEST = 'CHAT_PUSH_UNLOCK_REQUEST';
export const CHAT_NOT_READ_INCREMENT_REQUEST =
  'CHAT_NOT_READ_INCREMENT_REQUEST';
export const CHAT_NOT_READ_ARCHIVE_REQUEST = 'CHAT_NOT_READ_ARCHIVE_REQUEST';

export const CONTENT_REQUEST = 'CONTENT_REQUEST';
export const CONTENT_REQUEST_SUCCESS = 'CONTENT_REQUEST_SUCCESS';
export const CONTENT_DETAIL_REQUEST = 'CONTENT_DETAIL_REQUEST';
export const CONTENT_DETAIL_REQUEST_SUCCESS = 'CONTENT_DETAIL_REQUEST_SUCCESS';
export const CONTENT_RESET_REQUEST = 'CONTENT_RESET_REQUEST';

export const CAVABEN_REQUEST = 'CAVABEN_REQUEST';
export const CAVABEN_REQUEST_SUCCESS = 'CAVABEN_REQUEST_SUCCESS';
export const PRODUCTS_REQUEST_SUCCESS = 'PRODUCTS_REQUEST_SUCCESS';
export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST';
export const PRODUCT_DETAIL_REQUEST_SUCCESS = 'PRODUCT_DETAIL_REQUEST_SUCCESS';

export const NAVIGATE_REQUEST = 'NAVIGATE_REQUEST';
export const NAVIGATE_REQUEST_SUCCESS = 'NAVIGATE_REQUEST_SUCCESS';
export const CUSTOM_NAVIGATE_REQUEST = 'CUSTOM_NAVIGATE_REQUEST';
export const CUSTOM_NAVIGATE_REQUEST_SUCCESS =
  'CUSTOM_NAVIGATE_REQUEST_SUCCESS';

export const RSS_FEED_REQUEST = 'RSS_FEED_REQUEST';
export const RSS_FEED_REQUEST_SUCCESS = 'RSS_FEED_REQUEST_SUCCESS';

export const MENUS_REQUEST = 'MENUS_REQUEST';
export const MENUS_REQUEST_SUCCESS = 'MENUS_REQUEST_SUCCESS';
export const RESET_MENUS_REQUEST = 'RESET_MENUS_REQUEST';
export const PUBLIC_MENUS_REQUEST = 'PUBLIC_MENUS_REQUEST';
export const PUBLIC_MENUS_REQUEST_SUCCESS = 'PUBLIC_MENUS_REQUEST_SUCCESS';

export const REFRESH_REQUEST = 'REFRESH_REQUEST';
export const REFRESH_REQUEST_SUCCESS = 'REFRESH_REQUEST_SUCCESS';

export const SETTINGS_SUBMIT_REQUEST = 'SETTINGS_SUBMIT_REQUEST';
export const SETTINGS_SUBMIT_REQUEST_SUCCESS =
  'SETTINGS_SUBMIT_REQUEST_SUCCESS';
